### ISSUE TITLE
Tracking all KerasTuner public APIs added to the documentation

### ISSUE THREAD

**Issue by haifeng-jin** [keras-team/keras-io#1249]
This issue tracks all the public APIs of KerasTuner to make sure they are added to keras.io documentation.

- [x] keras_tuner.HyperModel
- [x] keras_tuner.Tuner
- [ ] keras_tuner.Objective
- [x] keras_tuner.HyperParameters
- [ ] keras_tuner.synchronized
- [x] keras_tuner.Oracle
- [x] keras_tuner.oracles.HyperbandOracle
- [ ] keras_tuner.oracles.GridSearchOracle
- [x] keras_tuner.oracles.BayesianOptimizationOracle
- [x] keras_tuner.oracles.RandomSearchOracle
- [x] keras_tuner.Hyperband
- [ ] keras_tuner.GridSearch
- [x] keras_tuner.SklearnTuner
- [x] keras_tuner.BayesianOptimization
- [x] keras_tuner.RandomSearch
- [ ] keras_tuner.applications.HyperImageAugment
- [x] keras_tuner.applications.HyperXception
- [ ] keras_tuner.applications.HyperEfficientNet
- [x] keras_tuner.applications.HyperResNet
